# SPDX-License-Identifier: MIT
# Healthy agent — up to date, all services running
FROM localhost/dirq_dirq-agent:latest
RUN dnf install -y openssl-3.2.2 curl nginx && dnf clean all
RUN echo "healthy" > /etc/dirq-role
