// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Anthony Green <green@moxielogic.com>

package server

import (
	"context"
	"crypto/ecdsa"
	"crypto/tls"
	"crypto/x509"
	"encoding/base64"
	"fmt"
	"log/slog"
	"net"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"sync"
	"syscall"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/keepalive"

	"github.com/atgreen/dirq/internal/config"
	"github.com/atgreen/dirq/internal/db"
	"github.com/atgreen/dirq/internal/signutil"
	"github.com/atgreen/dirq/internal/tlsutil"
	pb "github.com/atgreen/dirq/proto/dirq/v1"
)

// Config holds server configuration.
type Config struct {
	GRPCAddr            string // e.g. ":50051"
	HTTPAddr            string // e.g. ":8080"
	DBURL               string // PostgreSQL connection string
	PodID               string // unique identifier for this server pod
	MaxZoneLeaders      int    // topology: max zone leaders (default 50)
	MaxChildrenPerNode  int    // topology: max children per node (default 50)
	AuthDisabled        bool   // DIRQ_AUTH_DISABLED=true to allow anonymous API access
	RegistrationSecret  string // pre-shared secret for agent registration
	FileCfg             *config.File // parsed config file (for TLS/signing fallback)
}

// Server is the DirQ server.
type Server struct {
	pb.UnimplementedDirQServerServer

	cfg     Config
	topoCfg TopologyConfig
	db      db.DB
	log     *slog.Logger
	grpcSv  *grpc.Server
	httpSv  *http.Server
	signer  *signutil.Signer

	// oldSignerPubKeys holds raw Ed25519 public keys from previous signing keys.
	// Populated when DIRQ_SIGNING_PUB_OLD / signing_pub_old is configured.
	// Included in RegisterResponse and RenewCertResponse so agents can verify
	// messages during a key rotation.
	oldSignerPubKeys [][]byte

	// Connected zone leaders: agentID -> stream
	mu      sync.RWMutex
	streams map[string]*agentStream

	// Phase 2: exec sessions pending response
	execMu       sync.RWMutex
	execSessions map[string]*execSession

	// Session tokens: agentID -> token (generated during registration,
	// validated when an agent opens a stream).
	sessionMu     sync.RWMutex
	sessionTokens map[string]string

	// Agents currently being reassigned by the rebalancer. Their
	// disconnect from the old parent is expected — don't mark offline.
	reassigningMu sync.Mutex
	reassigning   map[string]time.Time

	// mTLS: when true, all gRPC methods except Register require a
	// valid client certificate. Enabled when the CA key is available.
	mtlsEnabled bool

	// CA for issuing per-agent client certificates during registration.
	tlsCfg      tlsutil.Config
	caCert      *x509.Certificate
	caKey       *ecdsa.PrivateKey
	certReloader *tlsutil.CertReloader

	// Dampening: tracks agents that were demoted but bounced back to
	// a direct server connection.  Prevents the rebalancer from
	// re-demoting them every cycle.
	demoteMu       sync.Mutex
	demoteCooldown map[string]demoteRecord

	// Bounded worker pool for fact upserts (#7). Prevents unbounded
	// goroutine creation when thousands of query results arrive at once.
	factCh chan factUpsert
}

type factUpsert struct {
	agentID string
	data    map[string]any
}

type agentStream struct {
	agentID      string
	capabilities []string
	send         chan *pb.ServerMessage
	cancel       context.CancelFunc
	reassigned   bool // true if this agent was demoted/reassigned — don't mark offline on stream close
}

// New creates a new DirQ server.
func New(cfg Config, database db.DB, log *slog.Logger) *Server {
	topoCfg := DefaultTopologyConfig()
	if cfg.MaxZoneLeaders > 0 {
		topoCfg.MaxZoneLeaders = cfg.MaxZoneLeaders
	}
	if cfg.MaxChildrenPerNode > 0 {
		topoCfg.MaxChildrenPerNode = cfg.MaxChildrenPerNode
	}

	return &Server{
		cfg:            cfg,
		topoCfg:        topoCfg,
		db:             database,
		log:            log,
		streams:        make(map[string]*agentStream),
		execSessions:   make(map[string]*execSession),
		sessionTokens:  make(map[string]string),
		reassigning:    make(map[string]time.Time),
		demoteCooldown: make(map[string]demoteRecord),
		factCh:         make(chan factUpsert, 4096),
	}
}

// writeAgentConfig generates /var/lib/dirq/agent.conf with inline TLS certs
// so administrators can copy a single file to onboard new agents.
func (s *Server) writeAgentConfig(tlsCfg tlsutil.Config) {
	outPath := filepath.Join(config.DataDir(), "agent.conf")

	hostname, _ := os.Hostname()
	// Extract just the port from GRPCAddr (which may be "0.0.0.0:50051" or ":50051").
	grpcPort := s.cfg.GRPCAddr
	if _, port, err := net.SplitHostPort(s.cfg.GRPCAddr); err == nil {
		grpcPort = ":" + port
	}
	serverAddr := hostname + grpcPort // e.g. "myserver:50051"

	var lines []string
	lines = append(lines,
		"# DirQ Agent Configuration (generated by dirq-server)",
		"# Copy this file to /etc/dirq/agent.conf on each agent host.",
		"#",
		"# Then: sudo systemctl enable --now dirq-agent",
		"",
		"server: "+serverAddr,
		"listen: 0.0.0.0:50052",
		"exec_enabled: false",
	)

	if s.cfg.RegistrationSecret != "" {
		lines = append(lines, "registration_secret: "+s.cfg.RegistrationSecret)
	}

	// Embed TLS CA cert inline. Agent cert/key are NOT included — each agent
	// receives its own mTLS client cert during registration with the agent ID
	// as the CN. The CA cert is needed so the agent can verify the server.
	if tlsCfg.Enabled() && tlsCfg.CAFile != "" {
		if caData, err := os.ReadFile(tlsCfg.CAFile); err == nil {
			lines = append(lines, "", "# TLS CA certificate (base64-encoded PEM)")
			lines = append(lines, "tls_ca_data: "+base64.StdEncoding.EncodeToString(caData))
		}
	}

	// Embed server signing public key so agents can verify messages
	// from registration onward (trust-on-first-use is not needed).
	if s.signer != nil {
		lines = append(lines, "", "# Server signing public key (base64-encoded Ed25519)")
		lines = append(lines, "signing_public_key: "+base64.StdEncoding.EncodeToString(s.signer.PublicKey()))
	}

	lines = append(lines, "")
	content := strings.Join(lines, "\n")

	if err := os.WriteFile(outPath, []byte(content), 0600); err != nil {
		s.log.Warn("failed to write agent config", "path", outPath, "error", err)
		return
	}
	s.log.Info("agent config written — copy to /etc/dirq/agent.conf on each agent host", "path", outPath)
}

// Start starts the gRPC and HTTP servers.
func (s *Server) Start(ctx context.Context) error {
	// Build gRPC server options.
	grpcOpts := []grpc.ServerOption{
		grpc.KeepaliveParams(keepalive.ServerParameters{
			Time:    30 * time.Second,
			Timeout: 10 * time.Second,
		}),
		grpc.KeepaliveEnforcementPolicy(keepalive.EnforcementPolicy{
			MinTime:             30 * time.Second,
			PermitWithoutStream: true,
		}),
	}

	// TLS is on by default. Auto-generates self-signed certs if none provided.
	tlsCfg := tlsutil.ConfigFromEnv(s.cfg.FileCfg)
	tlsCfg, err := tlsutil.EnsureCerts(tlsCfg, "server", s.log)
	if err != nil {
		return fmt.Errorf("TLS setup: %w", err)
	}
	s.tlsCfg = tlsCfg
	if tlsCfg.Enabled() {
		// Create a CertReloader for hot-reload support.
		reloader, err := tlsutil.NewCertReloader(tlsCfg.CertFile, tlsCfg.KeyFile)
		if err != nil {
			return fmt.Errorf("TLS cert reloader: %w", err)
		}
		s.certReloader = reloader

		// Use mixed-auth TLS: verify client certs if given, but don't
		// require them at the TLS layer. The mTLS interceptor enforces
		// per-method requirements (Register is exempt).
		creds, err := tlsutil.ServerCredentialsMixedAuthWithReloader(tlsCfg, reloader)
		if err != nil {
			return fmt.Errorf("TLS credentials: %w", err)
		}
		grpcOpts = append(grpcOpts, grpc.Creds(creds))

		// Enable mTLS enforcement if we have the CA key for issuing certs.
		if tlsCfg.CAKeyFile != "" {
			caCert, caKey, err := tlsutil.LoadCA(tlsCfg.CAFile, tlsCfg.CAKeyFile)
			if err != nil {
				return fmt.Errorf("load CA for mTLS: %w", err)
			}
			s.caCert = caCert
			s.caKey = caKey
			s.mtlsEnabled = true
			s.log.Info("mTLS enabled — agents receive client certs during registration")
		}
	} else {
		// Only reached when tls_disabled=true
	}

	// Add mTLS interceptors (they are no-ops when mtlsEnabled is false).
	grpcOpts = append(grpcOpts,
		grpc.UnaryInterceptor(s.mtlsUnaryInterceptor),
		grpc.StreamInterceptor(s.mtlsStreamInterceptor),
	)

	signer, err := signutil.EnsureServerSigner(signutil.ConfigFromEnv(s.cfg.FileCfg), s.log)
	if err != nil {
		return fmt.Errorf("signing setup: %w", err)
	}
	s.signer = signer

	// Load old signing key for rotation support.
	signCfg := signutil.ConfigFromEnv(s.cfg.FileCfg)
	if signCfg.OldPublicKeyFile != "" {
		oldPubData, err := os.ReadFile(signCfg.OldPublicKeyFile)
		if err != nil {
			s.log.Warn("failed to read old signing public key", "error", err)
		} else {
			decoded, err := base64.StdEncoding.DecodeString(strings.TrimSpace(string(oldPubData)))
			if err != nil {
				s.log.Warn("failed to decode old signing public key", "error", err)
			} else {
				s.oldSignerPubKeys = append(s.oldSignerPubKeys, decoded)
				s.log.Info("loaded old signing public key for rotation")
			}
		}
	}

	// Write a ready-to-deploy agent config file with inline TLS certs
	// and the server's signing public key.
	s.writeAgentConfig(tlsCfg)

	s.grpcSv = grpc.NewServer(grpcOpts...)
	pb.RegisterDirQServerServer(s.grpcSv, s)

	grpcLis, err := net.Listen("tcp", s.cfg.GRPCAddr)
	if err != nil {
		return fmt.Errorf("grpc listen: %w", err)
	}

	// HTTP/HTTPS server (REST API + Web UI)
	mux := s.setupHTTPRoutes()
	s.httpSv = &http.Server{
		Addr:    s.cfg.HTTPAddr,
		Handler: mux,
	}

	// Use HTTPS when TLS certs are available.
	if tlsCfg.Enabled() && tlsCfg.CertFile != "" {
		s.httpSv.TLSConfig = &tls.Config{
			GetCertificate: s.certReloader.GetCertificate,
			MinVersion:     tls.VersionTLS12,
		}
		s.log.Info("HTTPS enabled for REST API", "addr", s.cfg.HTTPAddr)
	} else {
		s.log.Warn("REST API running on plain HTTP")
	}

	httpLis, err := net.Listen("tcp", s.cfg.HTTPAddr)
	if err != nil {
		return fmt.Errorf("http listen: %w", err)
	}

	// Register this pod in the peers table
	if err := s.db.RegisterServerPeer(ctx, s.cfg.PodID, s.cfg.GRPCAddr); err != nil {
		s.log.Warn("failed to register server peer", "error", err)
	}

	// Start the stale-agent reaper, topology rebalancer, and fact workers.
	go s.startReaper(ctx)
	go s.startRebalancer(ctx)
	s.startFactWorkers(ctx, 8)

	capacity := s.topoCfg.MaxZoneLeaders * s.topoCfg.MaxChildrenPerNode * s.topoCfg.MaxChildrenPerNode
	s.log.Info("DirQ server starting",
		"grpc", s.cfg.GRPCAddr,
		"http", s.cfg.HTTPAddr,
		"pod_id", s.cfg.PodID,
		"max_zone_leaders", s.topoCfg.MaxZoneLeaders,
		"max_children", s.topoCfg.MaxChildrenPerNode,
		"max_capacity", capacity,
	)

	errCh := make(chan error, 2)
	go func() { errCh <- s.grpcSv.Serve(grpcLis) }()
	go func() {
		if s.httpSv.TLSConfig != nil {
			errCh <- s.httpSv.ServeTLS(httpLis, "", "") // certs already in TLSConfig
		} else {
			errCh <- s.httpSv.Serve(httpLis)
		}
	}()

	// Periodic TLS cert reload.
	if s.certReloader != nil {
		go func() {
			ticker := time.NewTicker(60 * time.Second)
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					if err := s.certReloader.Reload(); err != nil {
						s.log.Warn("TLS cert reload failed", "error", err)
					}
				}
			}
		}()

		// SIGHUP triggers immediate cert reload.
		sigCh := make(chan os.Signal, 1)
		signal.Notify(sigCh, syscall.SIGHUP)
		go func() {
			for {
				select {
				case <-ctx.Done():
					return
				case <-sigCh:
					s.log.Info("SIGHUP received, reloading TLS certificates")
					if err := s.certReloader.Reload(); err != nil {
						s.log.Error("TLS cert reload failed after SIGHUP", "error", err)
					}
				}
			}
		}()
	}

	select {
	case err := <-errCh:
		return err
	case <-ctx.Done():
		s.Stop()
		return ctx.Err()
	}
}

// Stop gracefully stops the server.
func (s *Server) Stop() {
	s.log.Info("shutting down")
	s.grpcSv.GracefulStop()
	s.httpSv.Close()
}
