// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/dirq/v1/dirq.proto

package dirqv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentRole int32

const (
	AgentRole_AGENT_ROLE_UNSPECIFIED AgentRole = 0
	AgentRole_AGENT_ROLE_LEAF        AgentRole = 1 // connects to a relay peer
	AgentRole_AGENT_ROLE_RELAY       AgentRole = 2 // accepts downstream + connects upstream
	AgentRole_AGENT_ROLE_ZONE_LEADER AgentRole = 3 // connects directly to the server
)

// Enum value maps for AgentRole.
var (
	AgentRole_name = map[int32]string{
		0: "AGENT_ROLE_UNSPECIFIED",
		1: "AGENT_ROLE_LEAF",
		2: "AGENT_ROLE_RELAY",
		3: "AGENT_ROLE_ZONE_LEADER",
	}
	AgentRole_value = map[string]int32{
		"AGENT_ROLE_UNSPECIFIED": 0,
		"AGENT_ROLE_LEAF":        1,
		"AGENT_ROLE_RELAY":       2,
		"AGENT_ROLE_ZONE_LEADER": 3,
	}
)

func (x AgentRole) Enum() *AgentRole {
	p := new(AgentRole)
	*p = x
	return p
}

func (x AgentRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentRole) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dirq_v1_dirq_proto_enumTypes[0].Descriptor()
}

func (AgentRole) Type() protoreflect.EnumType {
	return &file_proto_dirq_v1_dirq_proto_enumTypes[0]
}

func (x AgentRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentRole.Descriptor instead.
func (AgentRole) EnumDescriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`                                // "linux" or "windows"
	OsVersion     string                 `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"` // e.g. "RHEL 9.2", "Windows Server 2022"
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`                            // e.g. "amd64", "arm64"
	AgentVersion  string                 `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                                                           // supported query modules: "disk","cpu","memory",...
	ListenAddr    string                 `protobuf:"bytes,7,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`                                             // host:port this agent listens on for downstream peers
	Tags          map[string]string      `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // user-defined tags
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *RegisterRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

func (x *RegisterRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RegisterResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	AgentId                  string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // server-assigned unique ID
	Role                     AgentRole              `protobuf:"varint,2,opt,name=role,proto3,enum=dirq.v1.AgentRole" json:"role,omitempty"`
	Peers                    []*PeerInfo            `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`                                           // assigned upstream/sibling peers
	ZoneLeaderAddr           string                 `protobuf:"bytes,4,opt,name=zone_leader_addr,json=zoneLeaderAddr,proto3" json:"zone_leader_addr,omitempty"` // if this agent is not a zone leader, connect here
	HeartbeatIntervalSeconds int32                  `protobuf:"varint,5,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetRole() AgentRole {
	if x != nil {
		return x.Role
	}
	return AgentRole_AGENT_ROLE_UNSPECIFIED
}

func (x *RegisterResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *RegisterResponse) GetZoneLeaderAddr() string {
	if x != nil {
		return x.ZoneLeaderAddr
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"` // host:port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{2}
}

func (x *PeerInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PeerInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type PeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerRequest) Reset() {
	*x = PeerRequest{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerRequest) ProtoMessage() {}

func (x *PeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerRequest.ProtoReflect.Descriptor instead.
func (*PeerRequest) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{3}
}

func (x *PeerRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type PeerResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Peers          []*PeerInfo            `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	ZoneLeaderAddr string                 `protobuf:"bytes,3,opt,name=zone_leader_addr,json=zoneLeaderAddr,proto3" json:"zone_leader_addr,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PeerResponse) Reset() {
	*x = PeerResponse{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerResponse) ProtoMessage() {}

func (x *PeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerResponse.ProtoReflect.Descriptor instead.
func (*PeerResponse) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{4}
}

func (x *PeerResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *PeerResponse) GetZoneLeaderAddr() string {
	if x != nil {
		return x.ZoneLeaderAddr
	}
	return ""
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_QueryResult
	//	*AgentMessage_Hello
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{5}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetQueryResult() *QueryResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_QueryResult); ok {
			return x.QueryResult
		}
	}
	return nil
}

func (x *AgentMessage) GetHello() *AgentHello {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_QueryResult struct {
	QueryResult *QueryResult `protobuf:"bytes,2,opt,name=query_result,json=queryResult,proto3,oneof"`
}

type AgentMessage_Hello struct {
	Hello *AgentHello `protobuf:"bytes,3,opt,name=hello,proto3,oneof"`
}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_QueryResult) isAgentMessage_Payload() {}

func (*AgentMessage_Hello) isAgentMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_QueryRequest
	//	*ServerMessage_PeerUpdate
	//	*ServerMessage_UpdatePush
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{6}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetQueryRequest() *QueryRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_QueryRequest); ok {
			return x.QueryRequest
		}
	}
	return nil
}

func (x *ServerMessage) GetPeerUpdate() *PeerUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PeerUpdate); ok {
			return x.PeerUpdate
		}
	}
	return nil
}

func (x *ServerMessage) GetUpdatePush() *AgentUpdatePush {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_UpdatePush); ok {
			return x.UpdatePush
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_QueryRequest struct {
	QueryRequest *QueryRequest `protobuf:"bytes,1,opt,name=query_request,json=queryRequest,proto3,oneof"`
}

type ServerMessage_PeerUpdate struct {
	PeerUpdate *PeerUpdate `protobuf:"bytes,2,opt,name=peer_update,json=peerUpdate,proto3,oneof"`
}

type ServerMessage_UpdatePush struct {
	UpdatePush *AgentUpdatePush `protobuf:"bytes,3,opt,name=update_push,json=updatePush,proto3,oneof"`
}

func (*ServerMessage_QueryRequest) isServerMessage_Payload() {}

func (*ServerMessage_PeerUpdate) isServerMessage_Payload() {}

func (*ServerMessage_UpdatePush) isServerMessage_Payload() {}

// Agent identifies itself when opening a stream.
type AgentHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Capabilities  []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{7}
}

func (x *AgentHello) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentHello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Heartbeat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ConnectedPeers uint32                 `protobuf:"varint,3,opt,name=connected_peers,json=connectedPeers,proto3" json:"connected_peers,omitempty"` // how many downstream peers this agent has
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{8}
}

func (x *Heartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Heartbeat) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Heartbeat) GetConnectedPeers() uint32 {
	if x != nil {
		return x.ConnectedPeers
	}
	return 0
}

type QueryRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	QueryId  string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	RawQuery string                 `protobuf:"bytes,2,opt,name=raw_query,json=rawQuery,proto3" json:"raw_query,omitempty"` // the DirQ DSL expression
	// Pre-parsed for agents that do filtering:
	SelectFields   []string  `protobuf:"bytes,3,rep,name=select_fields,json=selectFields,proto3" json:"select_fields,omitempty"`
	Modules        []string  `protobuf:"bytes,4,rep,name=modules,proto3" json:"modules,omitempty"` // which modules to collect: "disk","cpu","memory"
	Filters        []*Filter `protobuf:"bytes,5,rep,name=filters,proto3" json:"filters,omitempty"`
	TimeoutSeconds int32     `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{9}
}

func (x *QueryRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryRequest) GetRawQuery() string {
	if x != nil {
		return x.RawQuery
	}
	return ""
}

func (x *QueryRequest) GetSelectFields() []string {
	if x != nil {
		return x.SelectFields
	}
	return nil
}

func (x *QueryRequest) GetModules() []string {
	if x != nil {
		return x.Modules
	}
	return nil
}

func (x *QueryRequest) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *QueryRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`       // e.g. "disk.pct_used"
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"` // e.g. ">", "=", "<", "!=", "LIKE"
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{10}
}

func (x *Filter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Filter) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Filter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"` // structured JSON result
	CollectedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{11}
}

func (x *QueryResult) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *QueryResult) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *QueryResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueryResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *QueryResult) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QueryResult) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

type PeerUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewPeers      []*PeerInfo            `protobuf:"bytes,1,rep,name=new_peers,json=newPeers,proto3" json:"new_peers,omitempty"`
	NewRole       AgentRole              `protobuf:"varint,2,opt,name=new_role,json=newRole,proto3,enum=dirq.v1.AgentRole" json:"new_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerUpdate) Reset() {
	*x = PeerUpdate{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerUpdate) ProtoMessage() {}

func (x *PeerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerUpdate.ProtoReflect.Descriptor instead.
func (*PeerUpdate) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{12}
}

func (x *PeerUpdate) GetNewPeers() []*PeerInfo {
	if x != nil {
		return x.NewPeers
	}
	return nil
}

func (x *PeerUpdate) GetNewRole() AgentRole {
	if x != nil {
		return x.NewRole
	}
	return AgentRole_AGENT_ROLE_UNSPECIFIED
}

type AgentUpdatePush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Binary        []byte                 `protobuf:"bytes,2,opt,name=binary,proto3" json:"binary,omitempty"`       // the new agent binary (chunked in practice)
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"` // Ed25519 signature
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`               // target OS
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`           // target arch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentUpdatePush) Reset() {
	*x = AgentUpdatePush{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentUpdatePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUpdatePush) ProtoMessage() {}

func (x *AgentUpdatePush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentUpdatePush.ProtoReflect.Descriptor instead.
func (*AgentUpdatePush) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{13}
}

func (x *AgentUpdatePush) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentUpdatePush) GetBinary() []byte {
	if x != nil {
		return x.Binary
	}
	return nil
}

func (x *AgentUpdatePush) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AgentUpdatePush) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentUpdatePush) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

var File_proto_dirq_v1_dirq_proto protoreflect.FileDescriptor

const file_proto_dirq_v1_dirq_proto_rawDesc = "" +
	"\n" +
	"\x18proto/dirq/v1/dirq.proto\x12\adirq.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xcb\x02\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x03 \x01(\tR\tosVersion\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x12\x1f\n" +
	"\vlisten_addr\x18\a \x01(\tR\n" +
	"listenAddr\x126\n" +
	"\x04tags\x18\b \x03(\v2\".dirq.v1.RegisterRequest.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe6\x01\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12&\n" +
	"\x04role\x18\x02 \x01(\x0e2\x12.dirq.v1.AgentRoleR\x04role\x12'\n" +
	"\x05peers\x18\x03 \x03(\v2\x11.dirq.v1.PeerInfoR\x05peers\x12(\n" +
	"\x10zone_leader_addr\x18\x04 \x01(\tR\x0ezoneLeaderAddr\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x05 \x01(\x05R\x18heartbeatIntervalSeconds\"9\n" +
	"\bPeerInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\"(\n" +
	"\vPeerRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"a\n" +
	"\fPeerResponse\x12'\n" +
	"\x05peers\x18\x02 \x03(\v2\x11.dirq.v1.PeerInfoR\x05peers\x12(\n" +
	"\x10zone_leader_addr\x18\x03 \x01(\tR\x0ezoneLeaderAddr\"\xb5\x01\n" +
	"\fAgentMessage\x122\n" +
	"\theartbeat\x18\x01 \x01(\v2\x12.dirq.v1.HeartbeatH\x00R\theartbeat\x129\n" +
	"\fquery_result\x18\x02 \x01(\v2\x14.dirq.v1.QueryResultH\x00R\vqueryResult\x12+\n" +
	"\x05hello\x18\x03 \x01(\v2\x13.dirq.v1.AgentHelloH\x00R\x05helloB\t\n" +
	"\apayload\"\xcd\x01\n" +
	"\rServerMessage\x12<\n" +
	"\rquery_request\x18\x01 \x01(\v2\x15.dirq.v1.QueryRequestH\x00R\fqueryRequest\x126\n" +
	"\vpeer_update\x18\x02 \x01(\v2\x13.dirq.v1.PeerUpdateH\x00R\n" +
	"peerUpdate\x12;\n" +
	"\vupdate_push\x18\x03 \x01(\v2\x18.dirq.v1.AgentUpdatePushH\x00R\n" +
	"updatePushB\t\n" +
	"\apayload\"K\n" +
	"\n" +
	"AgentHello\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\"\x89\x01\n" +
	"\tHeartbeat\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12'\n" +
	"\x0fconnected_peers\x18\x03 \x01(\rR\x0econnectedPeers\"\xd9\x01\n" +
	"\fQueryRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x1b\n" +
	"\traw_query\x18\x02 \x01(\tR\brawQuery\x12#\n" +
	"\rselect_fields\x18\x03 \x03(\tR\fselectFields\x12\x18\n" +
	"\amodules\x18\x04 \x03(\tR\amodules\x12)\n" +
	"\afilters\x18\x05 \x03(\v2\x0f.dirq.v1.FilterR\afilters\x12'\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\x05R\x0etimeoutSeconds\"P\n" +
	"\x06Filter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\xfb\x01\n" +
	"\vQueryResult\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12+\n" +
	"\x04data\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x04data\x12=\n" +
	"\fcollected_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\"k\n" +
	"\n" +
	"PeerUpdate\x12.\n" +
	"\tnew_peers\x18\x01 \x03(\v2\x11.dirq.v1.PeerInfoR\bnewPeers\x12-\n" +
	"\bnew_role\x18\x02 \x01(\x0e2\x12.dirq.v1.AgentRoleR\anewRole\"\x85\x01\n" +
	"\x0fAgentUpdatePush\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06binary\x18\x02 \x01(\fR\x06binary\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch*n\n" +
	"\tAgentRole\x12\x1a\n" +
	"\x16AGENT_ROLE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fAGENT_ROLE_LEAF\x10\x01\x12\x14\n" +
	"\x10AGENT_ROLE_RELAY\x10\x02\x12\x1a\n" +
	"\x16AGENT_ROLE_ZONE_LEADER\x10\x032\xcc\x01\n" +
	"\n" +
	"DirQServer\x12?\n" +
	"\bRegister\x12\x18.dirq.v1.RegisterRequest\x1a\x19.dirq.v1.RegisterResponse\x12@\n" +
	"\vAgentStream\x12\x15.dirq.v1.AgentMessage\x1a\x16.dirq.v1.ServerMessage(\x010\x01\x12;\n" +
	"\fRequestPeers\x12\x14.dirq.v1.PeerRequest\x1a\x15.dirq.v1.PeerResponse2M\n" +
	"\tDirQRelay\x12@\n" +
	"\vRelayStream\x12\x15.dirq.v1.AgentMessage\x1a\x16.dirq.v1.ServerMessage(\x010\x01B.Z,github.com/atgreen/dirq/proto/dirq/v1;dirqv1b\x06proto3"

var (
	file_proto_dirq_v1_dirq_proto_rawDescOnce sync.Once
	file_proto_dirq_v1_dirq_proto_rawDescData []byte
)

func file_proto_dirq_v1_dirq_proto_rawDescGZIP() []byte {
	file_proto_dirq_v1_dirq_proto_rawDescOnce.Do(func() {
		file_proto_dirq_v1_dirq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dirq_v1_dirq_proto_rawDesc), len(file_proto_dirq_v1_dirq_proto_rawDesc)))
	})
	return file_proto_dirq_v1_dirq_proto_rawDescData
}

var file_proto_dirq_v1_dirq_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_dirq_v1_dirq_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_dirq_v1_dirq_proto_goTypes = []any{
	(AgentRole)(0),                // 0: dirq.v1.AgentRole
	(*RegisterRequest)(nil),       // 1: dirq.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 2: dirq.v1.RegisterResponse
	(*PeerInfo)(nil),              // 3: dirq.v1.PeerInfo
	(*PeerRequest)(nil),           // 4: dirq.v1.PeerRequest
	(*PeerResponse)(nil),          // 5: dirq.v1.PeerResponse
	(*AgentMessage)(nil),          // 6: dirq.v1.AgentMessage
	(*ServerMessage)(nil),         // 7: dirq.v1.ServerMessage
	(*AgentHello)(nil),            // 8: dirq.v1.AgentHello
	(*Heartbeat)(nil),             // 9: dirq.v1.Heartbeat
	(*QueryRequest)(nil),          // 10: dirq.v1.QueryRequest
	(*Filter)(nil),                // 11: dirq.v1.Filter
	(*QueryResult)(nil),           // 12: dirq.v1.QueryResult
	(*PeerUpdate)(nil),            // 13: dirq.v1.PeerUpdate
	(*AgentUpdatePush)(nil),       // 14: dirq.v1.AgentUpdatePush
	nil,                           // 15: dirq.v1.RegisterRequest.TagsEntry
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 17: google.protobuf.Struct
}
var file_proto_dirq_v1_dirq_proto_depIdxs = []int32{
	15, // 0: dirq.v1.RegisterRequest.tags:type_name -> dirq.v1.RegisterRequest.TagsEntry
	0,  // 1: dirq.v1.RegisterResponse.role:type_name -> dirq.v1.AgentRole
	3,  // 2: dirq.v1.RegisterResponse.peers:type_name -> dirq.v1.PeerInfo
	3,  // 3: dirq.v1.PeerResponse.peers:type_name -> dirq.v1.PeerInfo
	9,  // 4: dirq.v1.AgentMessage.heartbeat:type_name -> dirq.v1.Heartbeat
	12, // 5: dirq.v1.AgentMessage.query_result:type_name -> dirq.v1.QueryResult
	8,  // 6: dirq.v1.AgentMessage.hello:type_name -> dirq.v1.AgentHello
	10, // 7: dirq.v1.ServerMessage.query_request:type_name -> dirq.v1.QueryRequest
	13, // 8: dirq.v1.ServerMessage.peer_update:type_name -> dirq.v1.PeerUpdate
	14, // 9: dirq.v1.ServerMessage.update_push:type_name -> dirq.v1.AgentUpdatePush
	16, // 10: dirq.v1.Heartbeat.timestamp:type_name -> google.protobuf.Timestamp
	11, // 11: dirq.v1.QueryRequest.filters:type_name -> dirq.v1.Filter
	17, // 12: dirq.v1.QueryResult.data:type_name -> google.protobuf.Struct
	16, // 13: dirq.v1.QueryResult.collected_at:type_name -> google.protobuf.Timestamp
	3,  // 14: dirq.v1.PeerUpdate.new_peers:type_name -> dirq.v1.PeerInfo
	0,  // 15: dirq.v1.PeerUpdate.new_role:type_name -> dirq.v1.AgentRole
	1,  // 16: dirq.v1.DirQServer.Register:input_type -> dirq.v1.RegisterRequest
	6,  // 17: dirq.v1.DirQServer.AgentStream:input_type -> dirq.v1.AgentMessage
	4,  // 18: dirq.v1.DirQServer.RequestPeers:input_type -> dirq.v1.PeerRequest
	6,  // 19: dirq.v1.DirQRelay.RelayStream:input_type -> dirq.v1.AgentMessage
	2,  // 20: dirq.v1.DirQServer.Register:output_type -> dirq.v1.RegisterResponse
	7,  // 21: dirq.v1.DirQServer.AgentStream:output_type -> dirq.v1.ServerMessage
	5,  // 22: dirq.v1.DirQServer.RequestPeers:output_type -> dirq.v1.PeerResponse
	7,  // 23: dirq.v1.DirQRelay.RelayStream:output_type -> dirq.v1.ServerMessage
	20, // [20:24] is the sub-list for method output_type
	16, // [16:20] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_dirq_v1_dirq_proto_init() }
func file_proto_dirq_v1_dirq_proto_init() {
	if File_proto_dirq_v1_dirq_proto != nil {
		return
	}
	file_proto_dirq_v1_dirq_proto_msgTypes[5].OneofWrappers = []any{
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_QueryResult)(nil),
		(*AgentMessage_Hello)(nil),
	}
	file_proto_dirq_v1_dirq_proto_msgTypes[6].OneofWrappers = []any{
		(*ServerMessage_QueryRequest)(nil),
		(*ServerMessage_PeerUpdate)(nil),
		(*ServerMessage_UpdatePush)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dirq_v1_dirq_proto_rawDesc), len(file_proto_dirq_v1_dirq_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_dirq_v1_dirq_proto_goTypes,
		DependencyIndexes: file_proto_dirq_v1_dirq_proto_depIdxs,
		EnumInfos:         file_proto_dirq_v1_dirq_proto_enumTypes,
		MessageInfos:      file_proto_dirq_v1_dirq_proto_msgTypes,
	}.Build()
	File_proto_dirq_v1_dirq_proto = out.File
	file_proto_dirq_v1_dirq_proto_goTypes = nil
	file_proto_dirq_v1_dirq_proto_depIdxs = nil
}
