// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Anthony Green <green@moxielogic.com>

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/dirq/v1/dirq.proto

package dirqv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DirQServer_Register_FullMethodName     = "/dirq.v1.DirQServer/Register"
	DirQServer_AgentStream_FullMethodName  = "/dirq.v1.DirQServer/AgentStream"
	DirQServer_RequestPeers_FullMethodName = "/dirq.v1.DirQServer/RequestPeers"
	DirQServer_RenewCert_FullMethodName    = "/dirq.v1.DirQServer/RenewCert"
)

// DirQServerClient is the client API for DirQServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DirQServerClient interface {
	// Agent calls this once at startup to register and get its peer assignment.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Zone leaders maintain a persistent bidirectional stream with the server.
	// Server pushes queries down; zone leader streams results back.
	AgentStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error)
	// Agent calls this when it loses all peers and needs reassignment.
	RequestPeers(ctx context.Context, in *PeerRequest, opts ...grpc.CallOption) (*PeerResponse, error)
	// Agent calls this to renew its mTLS certificate before expiry.
	// Requires a valid mTLS connection (CN must match agent_id).
	RenewCert(ctx context.Context, in *RenewCertRequest, opts ...grpc.CallOption) (*RenewCertResponse, error)
}

type dirQServerClient struct {
	cc grpc.ClientConnInterface
}

func NewDirQServerClient(cc grpc.ClientConnInterface) DirQServerClient {
	return &dirQServerClient{cc}
}

func (c *dirQServerClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, DirQServer_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dirQServerClient) AgentStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DirQServer_ServiceDesc.Streams[0], DirQServer_AgentStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DirQServer_AgentStreamClient = grpc.BidiStreamingClient[AgentMessage, ServerMessage]

func (c *dirQServerClient) RequestPeers(ctx context.Context, in *PeerRequest, opts ...grpc.CallOption) (*PeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerResponse)
	err := c.cc.Invoke(ctx, DirQServer_RequestPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dirQServerClient) RenewCert(ctx context.Context, in *RenewCertRequest, opts ...grpc.CallOption) (*RenewCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewCertResponse)
	err := c.cc.Invoke(ctx, DirQServer_RenewCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DirQServerServer is the server API for DirQServer service.
// All implementations must embed UnimplementedDirQServerServer
// for forward compatibility.
type DirQServerServer interface {
	// Agent calls this once at startup to register and get its peer assignment.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Zone leaders maintain a persistent bidirectional stream with the server.
	// Server pushes queries down; zone leader streams results back.
	AgentStream(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error
	// Agent calls this when it loses all peers and needs reassignment.
	RequestPeers(context.Context, *PeerRequest) (*PeerResponse, error)
	// Agent calls this to renew its mTLS certificate before expiry.
	// Requires a valid mTLS connection (CN must match agent_id).
	RenewCert(context.Context, *RenewCertRequest) (*RenewCertResponse, error)
	mustEmbedUnimplementedDirQServerServer()
}

// UnimplementedDirQServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDirQServerServer struct{}

func (UnimplementedDirQServerServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedDirQServerServer) AgentStream(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method AgentStream not implemented")
}
func (UnimplementedDirQServerServer) RequestPeers(context.Context, *PeerRequest) (*PeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestPeers not implemented")
}
func (UnimplementedDirQServerServer) RenewCert(context.Context, *RenewCertRequest) (*RenewCertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewCert not implemented")
}
func (UnimplementedDirQServerServer) mustEmbedUnimplementedDirQServerServer() {}
func (UnimplementedDirQServerServer) testEmbeddedByValue()                    {}

// UnsafeDirQServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DirQServerServer will
// result in compilation errors.
type UnsafeDirQServerServer interface {
	mustEmbedUnimplementedDirQServerServer()
}

func RegisterDirQServerServer(s grpc.ServiceRegistrar, srv DirQServerServer) {
	// If the following call panics, it indicates UnimplementedDirQServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DirQServer_ServiceDesc, srv)
}

func _DirQServer_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirQServerServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DirQServer_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirQServerServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirQServer_AgentStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DirQServerServer).AgentStream(&grpc.GenericServerStream[AgentMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DirQServer_AgentStreamServer = grpc.BidiStreamingServer[AgentMessage, ServerMessage]

func _DirQServer_RequestPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirQServerServer).RequestPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DirQServer_RequestPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirQServerServer).RequestPeers(ctx, req.(*PeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirQServer_RenewCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirQServerServer).RenewCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DirQServer_RenewCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirQServerServer).RenewCert(ctx, req.(*RenewCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DirQServer_ServiceDesc is the grpc.ServiceDesc for DirQServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DirQServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dirq.v1.DirQServer",
	HandlerType: (*DirQServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _DirQServer_Register_Handler,
		},
		{
			MethodName: "RequestPeers",
			Handler:    _DirQServer_RequestPeers_Handler,
		},
		{
			MethodName: "RenewCert",
			Handler:    _DirQServer_RenewCert_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AgentStream",
			Handler:       _DirQServer_AgentStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/dirq/v1/dirq.proto",
}

const (
	DirQRelay_RelayStream_FullMethodName = "/dirq.v1.DirQRelay/RelayStream"
)

// DirQRelayClient is the client API for DirQRelay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DirQRelayClient interface {
	// Downstream agent connects to upstream peer. Bidirectional stream for
	// relaying queries down and results up.
	RelayStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error)
}

type dirQRelayClient struct {
	cc grpc.ClientConnInterface
}

func NewDirQRelayClient(cc grpc.ClientConnInterface) DirQRelayClient {
	return &dirQRelayClient{cc}
}

func (c *dirQRelayClient) RelayStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DirQRelay_ServiceDesc.Streams[0], DirQRelay_RelayStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DirQRelay_RelayStreamClient = grpc.BidiStreamingClient[AgentMessage, ServerMessage]

// DirQRelayServer is the server API for DirQRelay service.
// All implementations must embed UnimplementedDirQRelayServer
// for forward compatibility.
type DirQRelayServer interface {
	// Downstream agent connects to upstream peer. Bidirectional stream for
	// relaying queries down and results up.
	RelayStream(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error
	mustEmbedUnimplementedDirQRelayServer()
}

// UnimplementedDirQRelayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDirQRelayServer struct{}

func (UnimplementedDirQRelayServer) RelayStream(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method RelayStream not implemented")
}
func (UnimplementedDirQRelayServer) mustEmbedUnimplementedDirQRelayServer() {}
func (UnimplementedDirQRelayServer) testEmbeddedByValue()                   {}

// UnsafeDirQRelayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DirQRelayServer will
// result in compilation errors.
type UnsafeDirQRelayServer interface {
	mustEmbedUnimplementedDirQRelayServer()
}

func RegisterDirQRelayServer(s grpc.ServiceRegistrar, srv DirQRelayServer) {
	// If the following call panics, it indicates UnimplementedDirQRelayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DirQRelay_ServiceDesc, srv)
}

func _DirQRelay_RelayStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DirQRelayServer).RelayStream(&grpc.GenericServerStream[AgentMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DirQRelay_RelayStreamServer = grpc.BidiStreamingServer[AgentMessage, ServerMessage]

// DirQRelay_ServiceDesc is the grpc.ServiceDesc for DirQRelay service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DirQRelay_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dirq.v1.DirQRelay",
	HandlerType: (*DirQRelayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RelayStream",
			Handler:       _DirQRelay_RelayStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/dirq/v1/dirq.proto",
}
