// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Anthony Green <green@moxielogic.com>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/dirq/v1/dirq.proto

package dirqv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentRole int32

const (
	AgentRole_AGENT_ROLE_UNSPECIFIED AgentRole = 0
	AgentRole_AGENT_ROLE_LEAF        AgentRole = 1 // connects to a relay peer
	AgentRole_AGENT_ROLE_RELAY       AgentRole = 2 // accepts downstream + connects upstream
	AgentRole_AGENT_ROLE_ZONE_LEADER AgentRole = 3 // connects directly to the server
)

// Enum value maps for AgentRole.
var (
	AgentRole_name = map[int32]string{
		0: "AGENT_ROLE_UNSPECIFIED",
		1: "AGENT_ROLE_LEAF",
		2: "AGENT_ROLE_RELAY",
		3: "AGENT_ROLE_ZONE_LEADER",
	}
	AgentRole_value = map[string]int32{
		"AGENT_ROLE_UNSPECIFIED": 0,
		"AGENT_ROLE_LEAF":        1,
		"AGENT_ROLE_RELAY":       2,
		"AGENT_ROLE_ZONE_LEADER": 3,
	}
)

func (x AgentRole) Enum() *AgentRole {
	p := new(AgentRole)
	*p = x
	return p
}

func (x AgentRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentRole) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dirq_v1_dirq_proto_enumTypes[0].Descriptor()
}

func (AgentRole) Type() protoreflect.EnumType {
	return &file_proto_dirq_v1_dirq_proto_enumTypes[0]
}

func (x AgentRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentRole.Descriptor instead.
func (AgentRole) EnumDescriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`                                // "linux" or "windows"
	OsVersion     string                 `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"` // e.g. "RHEL 9.2", "Windows Server 2022"
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`                            // e.g. "amd64", "arm64"
	AgentVersion  string                 `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                                                           // supported query modules: "disk","cpu","memory",...
	ListenAddr    string                 `protobuf:"bytes,7,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`                                             // host:port this agent listens on for downstream peers
	Tags          map[string]string      `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // user-defined tags
	ExecEnabled   bool                   `protobuf:"varint,9,opt,name=exec_enabled,json=execEnabled,proto3" json:"exec_enabled,omitempty"`                                         // Phase 2: whether this agent accepts exec requests
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *RegisterRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

func (x *RegisterRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RegisterRequest) GetExecEnabled() bool {
	if x != nil {
		return x.ExecEnabled
	}
	return false
}

type RegisterResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	AgentId                  string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // server-assigned unique ID
	Role                     AgentRole              `protobuf:"varint,2,opt,name=role,proto3,enum=dirq.v1.AgentRole" json:"role,omitempty"`
	Peers                    []*PeerInfo            `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`                                           // assigned upstream/sibling peers
	ZoneLeaderAddr           string                 `protobuf:"bytes,4,opt,name=zone_leader_addr,json=zoneLeaderAddr,proto3" json:"zone_leader_addr,omitempty"` // if this agent is not a zone leader, connect here
	HeartbeatIntervalSeconds int32                  `protobuf:"varint,5,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	ServerSigningPublicKey   []byte                 `protobuf:"bytes,6,opt,name=server_signing_public_key,json=serverSigningPublicKey,proto3" json:"server_signing_public_key,omitempty"` // Ed25519 public key for signed control messages
	ServerSigningKeyId       string                 `protobuf:"bytes,7,opt,name=server_signing_key_id,json=serverSigningKeyId,proto3" json:"server_signing_key_id,omitempty"`             // identifier/fingerprint for the signing key
	// Fallback parent addresses, tried in order if primary parent fails.
	// Chosen from different branches for fault isolation.
	FallbackAddrs []string `protobuf:"bytes,8,rep,name=fallback_addrs,json=fallbackAddrs,proto3" json:"fallback_addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetRole() AgentRole {
	if x != nil {
		return x.Role
	}
	return AgentRole_AGENT_ROLE_UNSPECIFIED
}

func (x *RegisterResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *RegisterResponse) GetZoneLeaderAddr() string {
	if x != nil {
		return x.ZoneLeaderAddr
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *RegisterResponse) GetServerSigningPublicKey() []byte {
	if x != nil {
		return x.ServerSigningPublicKey
	}
	return nil
}

func (x *RegisterResponse) GetServerSigningKeyId() string {
	if x != nil {
		return x.ServerSigningKeyId
	}
	return ""
}

func (x *RegisterResponse) GetFallbackAddrs() []string {
	if x != nil {
		return x.FallbackAddrs
	}
	return nil
}

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"` // host:port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{2}
}

func (x *PeerInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PeerInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type PeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerRequest) Reset() {
	*x = PeerRequest{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerRequest) ProtoMessage() {}

func (x *PeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerRequest.ProtoReflect.Descriptor instead.
func (*PeerRequest) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{3}
}

func (x *PeerRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type PeerResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Peers          []*PeerInfo            `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	ZoneLeaderAddr string                 `protobuf:"bytes,3,opt,name=zone_leader_addr,json=zoneLeaderAddr,proto3" json:"zone_leader_addr,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PeerResponse) Reset() {
	*x = PeerResponse{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerResponse) ProtoMessage() {}

func (x *PeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerResponse.ProtoReflect.Descriptor instead.
func (*PeerResponse) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{4}
}

func (x *PeerResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *PeerResponse) GetZoneLeaderAddr() string {
	if x != nil {
		return x.ZoneLeaderAddr
	}
	return ""
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_QueryResult
	//	*AgentMessage_Hello
	//	*AgentMessage_ExecResponse
	//	*AgentMessage_FileChunk
	//	*AgentMessage_FetchResponse
	//	*AgentMessage_AggregatedResult
	//	*AgentMessage_PeerDisconnected
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{5}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetQueryResult() *QueryResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_QueryResult); ok {
			return x.QueryResult
		}
	}
	return nil
}

func (x *AgentMessage) GetHello() *AgentHello {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetExecResponse() *ExecResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ExecResponse); ok {
			return x.ExecResponse
		}
	}
	return nil
}

func (x *AgentMessage) GetFileChunk() *FileChunk {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_FileChunk); ok {
			return x.FileChunk
		}
	}
	return nil
}

func (x *AgentMessage) GetFetchResponse() *FetchFileResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_FetchResponse); ok {
			return x.FetchResponse
		}
	}
	return nil
}

func (x *AgentMessage) GetAggregatedResult() *AggregatedQueryResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_AggregatedResult); ok {
			return x.AggregatedResult
		}
	}
	return nil
}

func (x *AgentMessage) GetPeerDisconnected() *PeerDisconnected {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_PeerDisconnected); ok {
			return x.PeerDisconnected
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_QueryResult struct {
	QueryResult *QueryResult `protobuf:"bytes,2,opt,name=query_result,json=queryResult,proto3,oneof"`
}

type AgentMessage_Hello struct {
	Hello *AgentHello `protobuf:"bytes,3,opt,name=hello,proto3,oneof"`
}

type AgentMessage_ExecResponse struct {
	ExecResponse *ExecResponse `protobuf:"bytes,4,opt,name=exec_response,json=execResponse,proto3,oneof"`
}

type AgentMessage_FileChunk struct {
	FileChunk *FileChunk `protobuf:"bytes,5,opt,name=file_chunk,json=fileChunk,proto3,oneof"`
}

type AgentMessage_FetchResponse struct {
	FetchResponse *FetchFileResponse `protobuf:"bytes,6,opt,name=fetch_response,json=fetchResponse,proto3,oneof"`
}

type AgentMessage_AggregatedResult struct {
	AggregatedResult *AggregatedQueryResult `protobuf:"bytes,7,opt,name=aggregated_result,json=aggregatedResult,proto3,oneof"` // batched results from subtree
}

type AgentMessage_PeerDisconnected struct {
	PeerDisconnected *PeerDisconnected `protobuf:"bytes,8,opt,name=peer_disconnected,json=peerDisconnected,proto3,oneof"` // child peer lost — propagate up
}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_QueryResult) isAgentMessage_Payload() {}

func (*AgentMessage_Hello) isAgentMessage_Payload() {}

func (*AgentMessage_ExecResponse) isAgentMessage_Payload() {}

func (*AgentMessage_FileChunk) isAgentMessage_Payload() {}

func (*AgentMessage_FetchResponse) isAgentMessage_Payload() {}

func (*AgentMessage_AggregatedResult) isAgentMessage_Payload() {}

func (*AgentMessage_PeerDisconnected) isAgentMessage_Payload() {}

// PeerDisconnected is sent upstream when a relay detects a child has
// disconnected. The server uses this to mark the agent (and its subtree)
// offline immediately, instead of waiting for heartbeat expiry.
type PeerDisconnected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // the agent that disconnected
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerDisconnected) Reset() {
	*x = PeerDisconnected{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerDisconnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerDisconnected) ProtoMessage() {}

func (x *PeerDisconnected) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerDisconnected.ProtoReflect.Descriptor instead.
func (*PeerDisconnected) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{6}
}

func (x *PeerDisconnected) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_QueryRequest
	//	*ServerMessage_PeerUpdate
	//	*ServerMessage_UpdatePush
	//	*ServerMessage_ExecRequest
	//	*ServerMessage_PutFile
	//	*ServerMessage_FetchFile
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	SignerKeyId   string                  `protobuf:"bytes,7,opt,name=signer_key_id,json=signerKeyId,proto3" json:"signer_key_id,omitempty"`
	SignedAtUnix  int64                   `protobuf:"varint,8,opt,name=signed_at_unix,json=signedAtUnix,proto3" json:"signed_at_unix,omitempty"`
	ExpiresAtUnix int64                   `protobuf:"varint,9,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	Signature     []byte                  `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{7}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetQueryRequest() *QueryRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_QueryRequest); ok {
			return x.QueryRequest
		}
	}
	return nil
}

func (x *ServerMessage) GetPeerUpdate() *PeerUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PeerUpdate); ok {
			return x.PeerUpdate
		}
	}
	return nil
}

func (x *ServerMessage) GetUpdatePush() *AgentUpdatePush {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_UpdatePush); ok {
			return x.UpdatePush
		}
	}
	return nil
}

func (x *ServerMessage) GetExecRequest() *ExecRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ExecRequest); ok {
			return x.ExecRequest
		}
	}
	return nil
}

func (x *ServerMessage) GetPutFile() *PutFileRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PutFile); ok {
			return x.PutFile
		}
	}
	return nil
}

func (x *ServerMessage) GetFetchFile() *FetchFileRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_FetchFile); ok {
			return x.FetchFile
		}
	}
	return nil
}

func (x *ServerMessage) GetSignerKeyId() string {
	if x != nil {
		return x.SignerKeyId
	}
	return ""
}

func (x *ServerMessage) GetSignedAtUnix() int64 {
	if x != nil {
		return x.SignedAtUnix
	}
	return 0
}

func (x *ServerMessage) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *ServerMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_QueryRequest struct {
	QueryRequest *QueryRequest `protobuf:"bytes,1,opt,name=query_request,json=queryRequest,proto3,oneof"`
}

type ServerMessage_PeerUpdate struct {
	PeerUpdate *PeerUpdate `protobuf:"bytes,2,opt,name=peer_update,json=peerUpdate,proto3,oneof"`
}

type ServerMessage_UpdatePush struct {
	UpdatePush *AgentUpdatePush `protobuf:"bytes,3,opt,name=update_push,json=updatePush,proto3,oneof"`
}

type ServerMessage_ExecRequest struct {
	ExecRequest *ExecRequest `protobuf:"bytes,4,opt,name=exec_request,json=execRequest,proto3,oneof"` // Phase 2: run command on agent
}

type ServerMessage_PutFile struct {
	PutFile *PutFileRequest `protobuf:"bytes,5,opt,name=put_file,json=putFile,proto3,oneof"` // Phase 2: write file to agent
}

type ServerMessage_FetchFile struct {
	FetchFile *FetchFileRequest `protobuf:"bytes,6,opt,name=fetch_file,json=fetchFile,proto3,oneof"` // Phase 2: read file from agent
}

func (*ServerMessage_QueryRequest) isServerMessage_Payload() {}

func (*ServerMessage_PeerUpdate) isServerMessage_Payload() {}

func (*ServerMessage_UpdatePush) isServerMessage_Payload() {}

func (*ServerMessage_ExecRequest) isServerMessage_Payload() {}

func (*ServerMessage_PutFile) isServerMessage_Payload() {}

func (*ServerMessage_FetchFile) isServerMessage_Payload() {}

// Agent identifies itself when opening a stream.
type AgentHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Capabilities  []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ExecEnabled   bool                   `protobuf:"varint,3,opt,name=exec_enabled,json=execEnabled,proto3" json:"exec_enabled,omitempty"` // Phase 2: whether exec is enabled on this agent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{8}
}

func (x *AgentHello) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentHello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentHello) GetExecEnabled() bool {
	if x != nil {
		return x.ExecEnabled
	}
	return false
}

type Heartbeat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ConnectedPeers uint32                 `protobuf:"varint,3,opt,name=connected_peers,json=connectedPeers,proto3" json:"connected_peers,omitempty"` // how many downstream peers this agent has
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{9}
}

func (x *Heartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Heartbeat) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Heartbeat) GetConnectedPeers() uint32 {
	if x != nil {
		return x.ConnectedPeers
	}
	return 0
}

type QueryRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	QueryId  string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	RawQuery string                 `protobuf:"bytes,2,opt,name=raw_query,json=rawQuery,proto3" json:"raw_query,omitempty"` // the DirQ DSL expression
	// Pre-parsed for agents that do filtering:
	SelectFields   []string  `protobuf:"bytes,3,rep,name=select_fields,json=selectFields,proto3" json:"select_fields,omitempty"`
	Modules        []string  `protobuf:"bytes,4,rep,name=modules,proto3" json:"modules,omitempty"` // which modules to collect: "disk","cpu","memory"
	Filters        []*Filter `protobuf:"bytes,5,rep,name=filters,proto3" json:"filters,omitempty"`
	TimeoutSeconds int32     `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// Target agent IDs. If empty, all agents execute (broadcast).
	// If populated, only agents in this list execute; others just relay.
	TargetAgentIds []string `protobuf:"bytes,7,rep,name=target_agent_ids,json=targetAgentIds,proto3" json:"target_agent_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{10}
}

func (x *QueryRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryRequest) GetRawQuery() string {
	if x != nil {
		return x.RawQuery
	}
	return ""
}

func (x *QueryRequest) GetSelectFields() []string {
	if x != nil {
		return x.SelectFields
	}
	return nil
}

func (x *QueryRequest) GetModules() []string {
	if x != nil {
		return x.Modules
	}
	return nil
}

func (x *QueryRequest) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *QueryRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *QueryRequest) GetTargetAgentIds() []string {
	if x != nil {
		return x.TargetAgentIds
	}
	return nil
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`       // e.g. "disk.pct_used"
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"` // e.g. ">", "=", "<", "!=", "LIKE"
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{11}
}

func (x *Filter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Filter) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Filter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"` // structured JSON result
	CollectedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{12}
}

func (x *QueryResult) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *QueryResult) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *QueryResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueryResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *QueryResult) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QueryResult) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

// AggregatedQueryResult carries batched results from a subtree.
// Relay agents and zone leaders buffer individual QueryResults from their
// children, then flush them as one aggregated message upstream. This reduces
// the number of messages the server receives from O(agents) to O(zone_leaders).
type AggregatedQueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Results       []*QueryResult         `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregatedQueryResult) Reset() {
	*x = AggregatedQueryResult{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedQueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedQueryResult) ProtoMessage() {}

func (x *AggregatedQueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedQueryResult.ProtoReflect.Descriptor instead.
func (*AggregatedQueryResult) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{13}
}

func (x *AggregatedQueryResult) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *AggregatedQueryResult) GetResults() []*QueryResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type PeerUpdate struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	NewPeers []*PeerInfo            `protobuf:"bytes,1,rep,name=new_peers,json=newPeers,proto3" json:"new_peers,omitempty"`
	NewRole  AgentRole              `protobuf:"varint,2,opt,name=new_role,json=newRole,proto3,enum=dirq.v1.AgentRole" json:"new_role,omitempty"`
	// Reconnect to this parent address. Agent should close the current
	// upstream connection and connect to this address instead.
	NewParentAddr string `protobuf:"bytes,3,opt,name=new_parent_addr,json=newParentAddr,proto3" json:"new_parent_addr,omitempty"`
	// Fallback addresses for the new parent.
	NewFallbackAddrs []string `protobuf:"bytes,4,rep,name=new_fallback_addrs,json=newFallbackAddrs,proto3" json:"new_fallback_addrs,omitempty"`
	// Target agent ID. If set, only the agent with this ID should apply
	// the update; other agents relay it downstream.
	TargetAgentId string `protobuf:"bytes,5,opt,name=target_agent_id,json=targetAgentId,proto3" json:"target_agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerUpdate) Reset() {
	*x = PeerUpdate{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerUpdate) ProtoMessage() {}

func (x *PeerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerUpdate.ProtoReflect.Descriptor instead.
func (*PeerUpdate) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{14}
}

func (x *PeerUpdate) GetNewPeers() []*PeerInfo {
	if x != nil {
		return x.NewPeers
	}
	return nil
}

func (x *PeerUpdate) GetNewRole() AgentRole {
	if x != nil {
		return x.NewRole
	}
	return AgentRole_AGENT_ROLE_UNSPECIFIED
}

func (x *PeerUpdate) GetNewParentAddr() string {
	if x != nil {
		return x.NewParentAddr
	}
	return ""
}

func (x *PeerUpdate) GetNewFallbackAddrs() []string {
	if x != nil {
		return x.NewFallbackAddrs
	}
	return nil
}

func (x *PeerUpdate) GetTargetAgentId() string {
	if x != nil {
		return x.TargetAgentId
	}
	return ""
}

type AgentUpdatePush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Binary        []byte                 `protobuf:"bytes,2,opt,name=binary,proto3" json:"binary,omitempty"`       // the new agent binary (chunked in practice)
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"` // Ed25519 signature
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`               // target OS
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`           // target arch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentUpdatePush) Reset() {
	*x = AgentUpdatePush{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentUpdatePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUpdatePush) ProtoMessage() {}

func (x *AgentUpdatePush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentUpdatePush.ProtoReflect.Descriptor instead.
func (*AgentUpdatePush) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{15}
}

func (x *AgentUpdatePush) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentUpdatePush) GetBinary() []byte {
	if x != nil {
		return x.Binary
	}
	return nil
}

func (x *AgentUpdatePush) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AgentUpdatePush) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentUpdatePush) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

// ExecRequest asks the agent to run a command.
type ExecRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                                                              // unique ID for this exec operation
	AgentId        string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                                                                    // target agent
	Command        string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`                                                                                   // command to execute (shell command string)
	Become         bool                   `protobuf:"varint,4,opt,name=become,proto3" json:"become,omitempty"`                                                                                    // run with privilege escalation (sudo/runas)
	BecomeUser     string                 `protobuf:"bytes,5,opt,name=become_user,json=becomeUser,proto3" json:"become_user,omitempty"`                                                           // user to become (default: root/Administrator)
	BecomeMethod   string                 `protobuf:"bytes,6,opt,name=become_method,json=becomeMethod,proto3" json:"become_method,omitempty"`                                                     // "sudo", "runas", etc.
	Environment    map[string]string      `protobuf:"bytes,7,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // extra env vars for the command
	TimeoutSeconds int32                  `protobuf:"varint,8,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// AAP attribution (for audit logging)
	AapJobId       string `protobuf:"bytes,9,opt,name=aap_job_id,json=aapJobId,proto3" json:"aap_job_id,omitempty"`
	AapJobTemplate string `protobuf:"bytes,10,opt,name=aap_job_template,json=aapJobTemplate,proto3" json:"aap_job_template,omitempty"`
	AapUser        string `protobuf:"bytes,11,opt,name=aap_user,json=aapUser,proto3" json:"aap_user,omitempty"`
	// stdin data piped to the process. Required for Ansible modules — they
	// send Python module code via stdin.
	Stdin []byte `protobuf:"bytes,12,opt,name=stdin,proto3" json:"stdin,omitempty"`
	// Script content. If set, agent writes to a temp file and executes it.
	// On Linux: preserves shebang, chmod +x, runs directly.
	// On Windows: writes as .ps1, runs with PowerShell.
	Script []byte `protobuf:"bytes,13,opt,name=script,proto3" json:"script,omitempty"`
	// Original filename (e.g. "deploy.sh", "check.ps1"). Used to pick the
	// right temp extension and execution method.
	ScriptName    string `protobuf:"bytes,14,opt,name=script_name,json=scriptName,proto3" json:"script_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{16}
}

func (x *ExecRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecRequest) GetBecome() bool {
	if x != nil {
		return x.Become
	}
	return false
}

func (x *ExecRequest) GetBecomeUser() string {
	if x != nil {
		return x.BecomeUser
	}
	return ""
}

func (x *ExecRequest) GetBecomeMethod() string {
	if x != nil {
		return x.BecomeMethod
	}
	return ""
}

func (x *ExecRequest) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *ExecRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecRequest) GetAapJobId() string {
	if x != nil {
		return x.AapJobId
	}
	return ""
}

func (x *ExecRequest) GetAapJobTemplate() string {
	if x != nil {
		return x.AapJobTemplate
	}
	return ""
}

func (x *ExecRequest) GetAapUser() string {
	if x != nil {
		return x.AapUser
	}
	return ""
}

func (x *ExecRequest) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

func (x *ExecRequest) GetScript() []byte {
	if x != nil {
		return x.Script
	}
	return nil
}

func (x *ExecRequest) GetScriptName() string {
	if x != nil {
		return x.ScriptName
	}
	return ""
}

// ExecResponse returns the result of command execution.
type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Rc            int32                  `protobuf:"varint,4,opt,name=rc,proto3" json:"rc,omitempty"` // exit code
	Stdout        []byte                 `protobuf:"bytes,5,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,6,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Success       bool                   `protobuf:"varint,7,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"` // agent-level error (e.g. exec disabled, timeout)
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{17}
}

func (x *ExecResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ExecResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ExecResponse) GetRc() int32 {
	if x != nil {
		return x.Rc
	}
	return 0
}

func (x *ExecResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *ExecResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ExecResponse) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

// PutFileRequest asks the agent to write a file to disk.
type PutFileRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RequestId  string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AgentId    string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	DestPath   string                 `protobuf:"bytes,3,opt,name=dest_path,json=destPath,proto3" json:"dest_path,omitempty"` // absolute path on the agent
	Content    []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                   // file content (max 100MB default)
	Mode       int32                  `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`                        // unix file mode (e.g. 0644), ignored on Windows
	Become     bool                   `protobuf:"varint,6,opt,name=become,proto3" json:"become,omitempty"`
	BecomeUser string                 `protobuf:"bytes,7,opt,name=become_user,json=becomeUser,proto3" json:"become_user,omitempty"`
	// AAP attribution
	AapJobId       string `protobuf:"bytes,8,opt,name=aap_job_id,json=aapJobId,proto3" json:"aap_job_id,omitempty"`
	AapJobTemplate string `protobuf:"bytes,9,opt,name=aap_job_template,json=aapJobTemplate,proto3" json:"aap_job_template,omitempty"`
	AapUser        string `protobuf:"bytes,10,opt,name=aap_user,json=aapUser,proto3" json:"aap_user,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PutFileRequest) Reset() {
	*x = PutFileRequest{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFileRequest) ProtoMessage() {}

func (x *PutFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFileRequest.ProtoReflect.Descriptor instead.
func (*PutFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{18}
}

func (x *PutFileRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PutFileRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PutFileRequest) GetDestPath() string {
	if x != nil {
		return x.DestPath
	}
	return ""
}

func (x *PutFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *PutFileRequest) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *PutFileRequest) GetBecome() bool {
	if x != nil {
		return x.Become
	}
	return false
}

func (x *PutFileRequest) GetBecomeUser() string {
	if x != nil {
		return x.BecomeUser
	}
	return ""
}

func (x *PutFileRequest) GetAapJobId() string {
	if x != nil {
		return x.AapJobId
	}
	return ""
}

func (x *PutFileRequest) GetAapJobTemplate() string {
	if x != nil {
		return x.AapJobTemplate
	}
	return ""
}

func (x *PutFileRequest) GetAapUser() string {
	if x != nil {
		return x.AapUser
	}
	return ""
}

// FetchFileRequest asks the agent to read a file from disk and send it back.
type FetchFileRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RequestId  string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AgentId    string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SrcPath    string                 `protobuf:"bytes,3,opt,name=src_path,json=srcPath,proto3" json:"src_path,omitempty"` // absolute path on the agent
	Become     bool                   `protobuf:"varint,4,opt,name=become,proto3" json:"become,omitempty"`
	BecomeUser string                 `protobuf:"bytes,5,opt,name=become_user,json=becomeUser,proto3" json:"become_user,omitempty"`
	// AAP attribution
	AapJobId       string `protobuf:"bytes,6,opt,name=aap_job_id,json=aapJobId,proto3" json:"aap_job_id,omitempty"`
	AapJobTemplate string `protobuf:"bytes,7,opt,name=aap_job_template,json=aapJobTemplate,proto3" json:"aap_job_template,omitempty"`
	AapUser        string `protobuf:"bytes,8,opt,name=aap_user,json=aapUser,proto3" json:"aap_user,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FetchFileRequest) Reset() {
	*x = FetchFileRequest{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchFileRequest) ProtoMessage() {}

func (x *FetchFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchFileRequest.ProtoReflect.Descriptor instead.
func (*FetchFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{19}
}

func (x *FetchFileRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FetchFileRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FetchFileRequest) GetSrcPath() string {
	if x != nil {
		return x.SrcPath
	}
	return ""
}

func (x *FetchFileRequest) GetBecome() bool {
	if x != nil {
		return x.Become
	}
	return false
}

func (x *FetchFileRequest) GetBecomeUser() string {
	if x != nil {
		return x.BecomeUser
	}
	return ""
}

func (x *FetchFileRequest) GetAapJobId() string {
	if x != nil {
		return x.AapJobId
	}
	return ""
}

func (x *FetchFileRequest) GetAapJobTemplate() string {
	if x != nil {
		return x.AapJobTemplate
	}
	return ""
}

func (x *FetchFileRequest) GetAapUser() string {
	if x != nil {
		return x.AapUser
	}
	return ""
}

// FetchFileResponse returns file content from the agent.
type FetchFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Content       []byte                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Mode          int32                  `protobuf:"varint,7,opt,name=mode,proto3" json:"mode,omitempty"` // original file mode
	Size          int64                  `protobuf:"varint,8,opt,name=size,proto3" json:"size,omitempty"` // file size in bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchFileResponse) Reset() {
	*x = FetchFileResponse{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchFileResponse) ProtoMessage() {}

func (x *FetchFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchFileResponse.ProtoReflect.Descriptor instead.
func (*FetchFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{20}
}

func (x *FetchFileResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FetchFileResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FetchFileResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *FetchFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FetchFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FetchFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FetchFileResponse) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FetchFileResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// FileChunk is the acknowledgement for a PutFileRequest.
type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dirq_v1_dirq_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_proto_dirq_v1_dirq_proto_rawDescGZIP(), []int{21}
}

func (x *FileChunk) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileChunk) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FileChunk) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *FileChunk) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FileChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_dirq_v1_dirq_proto protoreflect.FileDescriptor

const file_proto_dirq_v1_dirq_proto_rawDesc = "" +
	"\n" +
	"\x18proto/dirq/v1/dirq.proto\x12\adirq.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xee\x02\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x03 \x01(\tR\tosVersion\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x12\x1f\n" +
	"\vlisten_addr\x18\a \x01(\tR\n" +
	"listenAddr\x126\n" +
	"\x04tags\x18\b \x03(\v2\".dirq.v1.RegisterRequest.TagsEntryR\x04tags\x12!\n" +
	"\fexec_enabled\x18\t \x01(\bR\vexecEnabled\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfb\x02\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12&\n" +
	"\x04role\x18\x02 \x01(\x0e2\x12.dirq.v1.AgentRoleR\x04role\x12'\n" +
	"\x05peers\x18\x03 \x03(\v2\x11.dirq.v1.PeerInfoR\x05peers\x12(\n" +
	"\x10zone_leader_addr\x18\x04 \x01(\tR\x0ezoneLeaderAddr\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x05 \x01(\x05R\x18heartbeatIntervalSeconds\x129\n" +
	"\x19server_signing_public_key\x18\x06 \x01(\fR\x16serverSigningPublicKey\x121\n" +
	"\x15server_signing_key_id\x18\a \x01(\tR\x12serverSigningKeyId\x12%\n" +
	"\x0efallback_addrs\x18\b \x03(\tR\rfallbackAddrs\"9\n" +
	"\bPeerInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\"(\n" +
	"\vPeerRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"a\n" +
	"\fPeerResponse\x12'\n" +
	"\x05peers\x18\x02 \x03(\v2\x11.dirq.v1.PeerInfoR\x05peers\x12(\n" +
	"\x10zone_leader_addr\x18\x03 \x01(\tR\x0ezoneLeaderAddr\"\x86\x04\n" +
	"\fAgentMessage\x122\n" +
	"\theartbeat\x18\x01 \x01(\v2\x12.dirq.v1.HeartbeatH\x00R\theartbeat\x129\n" +
	"\fquery_result\x18\x02 \x01(\v2\x14.dirq.v1.QueryResultH\x00R\vqueryResult\x12+\n" +
	"\x05hello\x18\x03 \x01(\v2\x13.dirq.v1.AgentHelloH\x00R\x05hello\x12<\n" +
	"\rexec_response\x18\x04 \x01(\v2\x15.dirq.v1.ExecResponseH\x00R\fexecResponse\x123\n" +
	"\n" +
	"file_chunk\x18\x05 \x01(\v2\x12.dirq.v1.FileChunkH\x00R\tfileChunk\x12C\n" +
	"\x0efetch_response\x18\x06 \x01(\v2\x1a.dirq.v1.FetchFileResponseH\x00R\rfetchResponse\x12M\n" +
	"\x11aggregated_result\x18\a \x01(\v2\x1e.dirq.v1.AggregatedQueryResultH\x00R\x10aggregatedResult\x12H\n" +
	"\x11peer_disconnected\x18\b \x01(\v2\x19.dirq.v1.PeerDisconnectedH\x00R\x10peerDisconnectedB\t\n" +
	"\apayload\"-\n" +
	"\x10PeerDisconnected\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\x8a\x04\n" +
	"\rServerMessage\x12<\n" +
	"\rquery_request\x18\x01 \x01(\v2\x15.dirq.v1.QueryRequestH\x00R\fqueryRequest\x126\n" +
	"\vpeer_update\x18\x02 \x01(\v2\x13.dirq.v1.PeerUpdateH\x00R\n" +
	"peerUpdate\x12;\n" +
	"\vupdate_push\x18\x03 \x01(\v2\x18.dirq.v1.AgentUpdatePushH\x00R\n" +
	"updatePush\x129\n" +
	"\fexec_request\x18\x04 \x01(\v2\x14.dirq.v1.ExecRequestH\x00R\vexecRequest\x124\n" +
	"\bput_file\x18\x05 \x01(\v2\x17.dirq.v1.PutFileRequestH\x00R\aputFile\x12:\n" +
	"\n" +
	"fetch_file\x18\x06 \x01(\v2\x19.dirq.v1.FetchFileRequestH\x00R\tfetchFile\x12\"\n" +
	"\rsigner_key_id\x18\a \x01(\tR\vsignerKeyId\x12$\n" +
	"\x0esigned_at_unix\x18\b \x01(\x03R\fsignedAtUnix\x12&\n" +
	"\x0fexpires_at_unix\x18\t \x01(\x03R\rexpiresAtUnix\x12\x1c\n" +
	"\tsignature\x18\n" +
	" \x01(\fR\tsignatureB\t\n" +
	"\apayload\"n\n" +
	"\n" +
	"AgentHello\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x12!\n" +
	"\fexec_enabled\x18\x03 \x01(\bR\vexecEnabled\"\x89\x01\n" +
	"\tHeartbeat\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12'\n" +
	"\x0fconnected_peers\x18\x03 \x01(\rR\x0econnectedPeers\"\x83\x02\n" +
	"\fQueryRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x1b\n" +
	"\traw_query\x18\x02 \x01(\tR\brawQuery\x12#\n" +
	"\rselect_fields\x18\x03 \x03(\tR\fselectFields\x12\x18\n" +
	"\amodules\x18\x04 \x03(\tR\amodules\x12)\n" +
	"\afilters\x18\x05 \x03(\v2\x0f.dirq.v1.FilterR\afilters\x12'\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\x05R\x0etimeoutSeconds\x12(\n" +
	"\x10target_agent_ids\x18\a \x03(\tR\x0etargetAgentIds\"P\n" +
	"\x06Filter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\xfb\x01\n" +
	"\vQueryResult\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12+\n" +
	"\x04data\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x04data\x12=\n" +
	"\fcollected_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\"b\n" +
	"\x15AggregatedQueryResult\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12.\n" +
	"\aresults\x18\x02 \x03(\v2\x14.dirq.v1.QueryResultR\aresults\"\xe9\x01\n" +
	"\n" +
	"PeerUpdate\x12.\n" +
	"\tnew_peers\x18\x01 \x03(\v2\x11.dirq.v1.PeerInfoR\bnewPeers\x12-\n" +
	"\bnew_role\x18\x02 \x01(\x0e2\x12.dirq.v1.AgentRoleR\anewRole\x12&\n" +
	"\x0fnew_parent_addr\x18\x03 \x01(\tR\rnewParentAddr\x12,\n" +
	"\x12new_fallback_addrs\x18\x04 \x03(\tR\x10newFallbackAddrs\x12&\n" +
	"\x0ftarget_agent_id\x18\x05 \x01(\tR\rtargetAgentId\"\x85\x01\n" +
	"\x0fAgentUpdatePush\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06binary\x18\x02 \x01(\fR\x06binary\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\"\xa3\x04\n" +
	"\vExecRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x16\n" +
	"\x06become\x18\x04 \x01(\bR\x06become\x12\x1f\n" +
	"\vbecome_user\x18\x05 \x01(\tR\n" +
	"becomeUser\x12#\n" +
	"\rbecome_method\x18\x06 \x01(\tR\fbecomeMethod\x12G\n" +
	"\venvironment\x18\a \x03(\v2%.dirq.v1.ExecRequest.EnvironmentEntryR\venvironment\x12'\n" +
	"\x0ftimeout_seconds\x18\b \x01(\x05R\x0etimeoutSeconds\x12\x1c\n" +
	"\n" +
	"aap_job_id\x18\t \x01(\tR\baapJobId\x12(\n" +
	"\x10aap_job_template\x18\n" +
	" \x01(\tR\x0eaapJobTemplate\x12\x19\n" +
	"\baap_user\x18\v \x01(\tR\aaapUser\x12\x14\n" +
	"\x05stdin\x18\f \x01(\fR\x05stdin\x12\x16\n" +
	"\x06script\x18\r \x01(\fR\x06script\x12\x1f\n" +
	"\vscript_name\x18\x0e \x01(\tR\n" +
	"scriptName\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcc\x02\n" +
	"\fExecResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02rc\x18\x04 \x01(\x05R\x02rc\x12\x16\n" +
	"\x06stdout\x18\x05 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x06 \x01(\fR\x06stderr\x12\x18\n" +
	"\asuccess\x18\a \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"\xb1\x02\n" +
	"\x0ePutFileRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1b\n" +
	"\tdest_path\x18\x03 \x01(\tR\bdestPath\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\x05R\x04mode\x12\x16\n" +
	"\x06become\x18\x06 \x01(\bR\x06become\x12\x1f\n" +
	"\vbecome_user\x18\a \x01(\tR\n" +
	"becomeUser\x12\x1c\n" +
	"\n" +
	"aap_job_id\x18\b \x01(\tR\baapJobId\x12(\n" +
	"\x10aap_job_template\x18\t \x01(\tR\x0eaapJobTemplate\x12\x19\n" +
	"\baap_user\x18\n" +
	" \x01(\tR\aaapUser\"\x83\x02\n" +
	"\x10FetchFileRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x19\n" +
	"\bsrc_path\x18\x03 \x01(\tR\asrcPath\x12\x16\n" +
	"\x06become\x18\x04 \x01(\bR\x06become\x12\x1f\n" +
	"\vbecome_user\x18\x05 \x01(\tR\n" +
	"becomeUser\x12\x1c\n" +
	"\n" +
	"aap_job_id\x18\x06 \x01(\tR\baapJobId\x12(\n" +
	"\x10aap_job_template\x18\a \x01(\tR\x0eaapJobTemplate\x12\x19\n" +
	"\baap_user\x18\b \x01(\tR\aaapUser\"\xdb\x01\n" +
	"\x11FetchFileResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x18\n" +
	"\acontent\x18\x06 \x01(\fR\acontent\x12\x12\n" +
	"\x04mode\x18\a \x01(\x05R\x04mode\x12\x12\n" +
	"\x04size\x18\b \x01(\x03R\x04size\"\x91\x01\n" +
	"\tFileChunk\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error*n\n" +
	"\tAgentRole\x12\x1a\n" +
	"\x16AGENT_ROLE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fAGENT_ROLE_LEAF\x10\x01\x12\x14\n" +
	"\x10AGENT_ROLE_RELAY\x10\x02\x12\x1a\n" +
	"\x16AGENT_ROLE_ZONE_LEADER\x10\x032\xcc\x01\n" +
	"\n" +
	"DirQServer\x12?\n" +
	"\bRegister\x12\x18.dirq.v1.RegisterRequest\x1a\x19.dirq.v1.RegisterResponse\x12@\n" +
	"\vAgentStream\x12\x15.dirq.v1.AgentMessage\x1a\x16.dirq.v1.ServerMessage(\x010\x01\x12;\n" +
	"\fRequestPeers\x12\x14.dirq.v1.PeerRequest\x1a\x15.dirq.v1.PeerResponse2M\n" +
	"\tDirQRelay\x12@\n" +
	"\vRelayStream\x12\x15.dirq.v1.AgentMessage\x1a\x16.dirq.v1.ServerMessage(\x010\x01B.Z,github.com/atgreen/dirq/proto/dirq/v1;dirqv1b\x06proto3"

var (
	file_proto_dirq_v1_dirq_proto_rawDescOnce sync.Once
	file_proto_dirq_v1_dirq_proto_rawDescData []byte
)

func file_proto_dirq_v1_dirq_proto_rawDescGZIP() []byte {
	file_proto_dirq_v1_dirq_proto_rawDescOnce.Do(func() {
		file_proto_dirq_v1_dirq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dirq_v1_dirq_proto_rawDesc), len(file_proto_dirq_v1_dirq_proto_rawDesc)))
	})
	return file_proto_dirq_v1_dirq_proto_rawDescData
}

var file_proto_dirq_v1_dirq_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_dirq_v1_dirq_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_dirq_v1_dirq_proto_goTypes = []any{
	(AgentRole)(0),                // 0: dirq.v1.AgentRole
	(*RegisterRequest)(nil),       // 1: dirq.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 2: dirq.v1.RegisterResponse
	(*PeerInfo)(nil),              // 3: dirq.v1.PeerInfo
	(*PeerRequest)(nil),           // 4: dirq.v1.PeerRequest
	(*PeerResponse)(nil),          // 5: dirq.v1.PeerResponse
	(*AgentMessage)(nil),          // 6: dirq.v1.AgentMessage
	(*PeerDisconnected)(nil),      // 7: dirq.v1.PeerDisconnected
	(*ServerMessage)(nil),         // 8: dirq.v1.ServerMessage
	(*AgentHello)(nil),            // 9: dirq.v1.AgentHello
	(*Heartbeat)(nil),             // 10: dirq.v1.Heartbeat
	(*QueryRequest)(nil),          // 11: dirq.v1.QueryRequest
	(*Filter)(nil),                // 12: dirq.v1.Filter
	(*QueryResult)(nil),           // 13: dirq.v1.QueryResult
	(*AggregatedQueryResult)(nil), // 14: dirq.v1.AggregatedQueryResult
	(*PeerUpdate)(nil),            // 15: dirq.v1.PeerUpdate
	(*AgentUpdatePush)(nil),       // 16: dirq.v1.AgentUpdatePush
	(*ExecRequest)(nil),           // 17: dirq.v1.ExecRequest
	(*ExecResponse)(nil),          // 18: dirq.v1.ExecResponse
	(*PutFileRequest)(nil),        // 19: dirq.v1.PutFileRequest
	(*FetchFileRequest)(nil),      // 20: dirq.v1.FetchFileRequest
	(*FetchFileResponse)(nil),     // 21: dirq.v1.FetchFileResponse
	(*FileChunk)(nil),             // 22: dirq.v1.FileChunk
	nil,                           // 23: dirq.v1.RegisterRequest.TagsEntry
	nil,                           // 24: dirq.v1.ExecRequest.EnvironmentEntry
	(*timestamppb.Timestamp)(nil), // 25: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 26: google.protobuf.Struct
}
var file_proto_dirq_v1_dirq_proto_depIdxs = []int32{
	23, // 0: dirq.v1.RegisterRequest.tags:type_name -> dirq.v1.RegisterRequest.TagsEntry
	0,  // 1: dirq.v1.RegisterResponse.role:type_name -> dirq.v1.AgentRole
	3,  // 2: dirq.v1.RegisterResponse.peers:type_name -> dirq.v1.PeerInfo
	3,  // 3: dirq.v1.PeerResponse.peers:type_name -> dirq.v1.PeerInfo
	10, // 4: dirq.v1.AgentMessage.heartbeat:type_name -> dirq.v1.Heartbeat
	13, // 5: dirq.v1.AgentMessage.query_result:type_name -> dirq.v1.QueryResult
	9,  // 6: dirq.v1.AgentMessage.hello:type_name -> dirq.v1.AgentHello
	18, // 7: dirq.v1.AgentMessage.exec_response:type_name -> dirq.v1.ExecResponse
	22, // 8: dirq.v1.AgentMessage.file_chunk:type_name -> dirq.v1.FileChunk
	21, // 9: dirq.v1.AgentMessage.fetch_response:type_name -> dirq.v1.FetchFileResponse
	14, // 10: dirq.v1.AgentMessage.aggregated_result:type_name -> dirq.v1.AggregatedQueryResult
	7,  // 11: dirq.v1.AgentMessage.peer_disconnected:type_name -> dirq.v1.PeerDisconnected
	11, // 12: dirq.v1.ServerMessage.query_request:type_name -> dirq.v1.QueryRequest
	15, // 13: dirq.v1.ServerMessage.peer_update:type_name -> dirq.v1.PeerUpdate
	16, // 14: dirq.v1.ServerMessage.update_push:type_name -> dirq.v1.AgentUpdatePush
	17, // 15: dirq.v1.ServerMessage.exec_request:type_name -> dirq.v1.ExecRequest
	19, // 16: dirq.v1.ServerMessage.put_file:type_name -> dirq.v1.PutFileRequest
	20, // 17: dirq.v1.ServerMessage.fetch_file:type_name -> dirq.v1.FetchFileRequest
	25, // 18: dirq.v1.Heartbeat.timestamp:type_name -> google.protobuf.Timestamp
	12, // 19: dirq.v1.QueryRequest.filters:type_name -> dirq.v1.Filter
	26, // 20: dirq.v1.QueryResult.data:type_name -> google.protobuf.Struct
	25, // 21: dirq.v1.QueryResult.collected_at:type_name -> google.protobuf.Timestamp
	13, // 22: dirq.v1.AggregatedQueryResult.results:type_name -> dirq.v1.QueryResult
	3,  // 23: dirq.v1.PeerUpdate.new_peers:type_name -> dirq.v1.PeerInfo
	0,  // 24: dirq.v1.PeerUpdate.new_role:type_name -> dirq.v1.AgentRole
	24, // 25: dirq.v1.ExecRequest.environment:type_name -> dirq.v1.ExecRequest.EnvironmentEntry
	25, // 26: dirq.v1.ExecResponse.started_at:type_name -> google.protobuf.Timestamp
	25, // 27: dirq.v1.ExecResponse.finished_at:type_name -> google.protobuf.Timestamp
	1,  // 28: dirq.v1.DirQServer.Register:input_type -> dirq.v1.RegisterRequest
	6,  // 29: dirq.v1.DirQServer.AgentStream:input_type -> dirq.v1.AgentMessage
	4,  // 30: dirq.v1.DirQServer.RequestPeers:input_type -> dirq.v1.PeerRequest
	6,  // 31: dirq.v1.DirQRelay.RelayStream:input_type -> dirq.v1.AgentMessage
	2,  // 32: dirq.v1.DirQServer.Register:output_type -> dirq.v1.RegisterResponse
	8,  // 33: dirq.v1.DirQServer.AgentStream:output_type -> dirq.v1.ServerMessage
	5,  // 34: dirq.v1.DirQServer.RequestPeers:output_type -> dirq.v1.PeerResponse
	8,  // 35: dirq.v1.DirQRelay.RelayStream:output_type -> dirq.v1.ServerMessage
	32, // [32:36] is the sub-list for method output_type
	28, // [28:32] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_proto_dirq_v1_dirq_proto_init() }
func file_proto_dirq_v1_dirq_proto_init() {
	if File_proto_dirq_v1_dirq_proto != nil {
		return
	}
	file_proto_dirq_v1_dirq_proto_msgTypes[5].OneofWrappers = []any{
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_QueryResult)(nil),
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_ExecResponse)(nil),
		(*AgentMessage_FileChunk)(nil),
		(*AgentMessage_FetchResponse)(nil),
		(*AgentMessage_AggregatedResult)(nil),
		(*AgentMessage_PeerDisconnected)(nil),
	}
	file_proto_dirq_v1_dirq_proto_msgTypes[7].OneofWrappers = []any{
		(*ServerMessage_QueryRequest)(nil),
		(*ServerMessage_PeerUpdate)(nil),
		(*ServerMessage_UpdatePush)(nil),
		(*ServerMessage_ExecRequest)(nil),
		(*ServerMessage_PutFile)(nil),
		(*ServerMessage_FetchFile)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dirq_v1_dirq_proto_rawDesc), len(file_proto_dirq_v1_dirq_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_dirq_v1_dirq_proto_goTypes,
		DependencyIndexes: file_proto_dirq_v1_dirq_proto_depIdxs,
		EnumInfos:         file_proto_dirq_v1_dirq_proto_enumTypes,
		MessageInfos:      file_proto_dirq_v1_dirq_proto_msgTypes,
	}.Build()
	File_proto_dirq_v1_dirq_proto = out.File
	file_proto_dirq_v1_dirq_proto_goTypes = nil
	file_proto_dirq_v1_dirq_proto_depIdxs = nil
}
