; DirQ Agent - Windows Installer
; NSIS Script
;
; SPDX-License-Identifier: MIT
; Copyright (C) 2026 Anthony Green <green@moxielogic.com>

!include "MUI2.nsh"
!include "FileFunc.nsh"
!include "nsDialogs.nsh"

; ============================================================================
; General Configuration
; ============================================================================

!define PRODUCT_NAME "DirQ Agent"
!define PRODUCT_SHORT "DirQ"
!define PRODUCT_PUBLISHER "Anthony Green"
!define PRODUCT_WEB_SITE "https://github.com/atgreen/dirq"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_SHORT}Agent"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
!define SERVICE_NAME "DirQAgent"
!define CONFIG_DIR "$COMMONAPPDATA\dirq"

; Version is passed from command line: makensis /DVERSION=0.2.0 dirq-agent.nsi
!ifndef VERSION
  !define VERSION "0.0.0"
!endif

Name "${PRODUCT_NAME} ${VERSION}"
OutFile "dirq-agent-${VERSION}-setup.exe"
InstallDir "$PROGRAMFILES64\DirQ"
InstallDirRegKey HKLM "Software\${PRODUCT_SHORT}" "InstallDir"
RequestExecutionLevel admin
SetCompressor /SOLID lzma

; ============================================================================
; Variables
; ============================================================================

Var ServerAddr
Var ExecEnabled

; ============================================================================
; Modern UI Configuration
; ============================================================================

!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME

; License page
!insertmacro MUI_PAGE_LICENSE "..\..\..\LICENSE"

; Directory page
!insertmacro MUI_PAGE_DIRECTORY

; Configuration page
Page custom ConfigPage ConfigPageLeave

; Instfiles page
!insertmacro MUI_PAGE_INSTFILES

; Finish page
!define MUI_FINISHPAGE_TEXT "${PRODUCT_NAME} has been installed and the service is running.$\r$\n$\r$\nConfiguration: ${CONFIG_DIR}\agent.conf"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

; Language
!insertmacro MUI_LANGUAGE "English"

; ============================================================================
; Configuration Page
; ============================================================================

Function ConfigPage
  nsDialogs::Create 1018
  Pop $0

  ${NSD_CreateLabel} 0 0 100% 24u "Configure the DirQ agent. These settings are written to ${CONFIG_DIR}\agent.conf and can be changed later."
  Pop $0

  ${NSD_CreateLabel} 0 40u 120u 12u "Server address:"
  Pop $0
  ${NSD_CreateText} 130u 38u 200u 14u "localhost:50051"
  Pop $ServerAddr

  ${NSD_CreateCheckBox} 0 65u 200u 12u "Enable remote execution"
  Pop $ExecEnabled

  nsDialogs::Show
FunctionEnd

Function ConfigPageLeave
  ${NSD_GetText} $ServerAddr $ServerAddr
  ${NSD_GetState} $ExecEnabled $ExecEnabled
FunctionEnd

; ============================================================================
; Installer Sections
; ============================================================================

Section "DirQ Agent" SEC_CORE
  SectionIn RO  ; Required section

  ; Stop existing service if running.
  nsExec::ExecToLog 'sc stop ${SERVICE_NAME}'
  Sleep 2000

  ; Install binary.
  SetOutPath "$INSTDIR"
  File "..\..\..\bin\dirq-agent.exe"
  File "..\..\..\LICENSE"
  File "..\..\..\README.md"

  ; Write config file.
  CreateDirectory "${CONFIG_DIR}"

  ; Determine exec_enabled value.
  StrCmp $ExecEnabled ${BST_CHECKED} 0 +3
    StrCpy $1 "true"
    Goto +2
    StrCpy $1 "false"

  FileOpen $0 "${CONFIG_DIR}\agent.conf" w
  FileWrite $0 "# DirQ Agent Configuration$\r$\n"
  FileWrite $0 "# Generated by installer v${VERSION}$\r$\n"
  FileWrite $0 "$\r$\n"
  FileWrite $0 "server: $ServerAddr$\r$\n"
  FileWrite $0 "listen: 0.0.0.0:50052$\r$\n"
  FileWrite $0 "exec_enabled: $1$\r$\n"
  FileWrite $0 "$\r$\n"
  FileWrite $0 "tags:$\r$\n"
  FileWrite $0 "  os: windows$\r$\n"
  FileClose $0

  ; Install and start service.
  nsExec::ExecToLog '"$INSTDIR\dirq-agent.exe" install'
  nsExec::ExecToLog 'sc start ${SERVICE_NAME}'

  ; Add firewall rule for relay port.
  nsExec::ExecToLog 'netsh advfirewall firewall add rule name="DirQ Agent" dir=in action=allow protocol=tcp localport=50052'

  ; Store installation folder.
  WriteRegStr HKLM "Software\${PRODUCT_SHORT}" "InstallDir" "$INSTDIR"

  ; Create uninstaller.
  WriteUninstaller "$INSTDIR\uninstall.exe"

  ; Add to Add/Remove Programs.
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "${PRODUCT_NAME}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninstall.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "InstallLocation" "$INSTDIR"
  WriteRegDWORD ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "NoModify" 1
  WriteRegDWORD ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "NoRepair" 1

  ; Calculate installed size.
  ${GetSize} "$INSTDIR" "/S=0K" $0 $1 $2
  IntFmt $0 "0x%08X" $0
  WriteRegDWORD ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "EstimatedSize" "$0"
SectionEnd

; ============================================================================
; Uninstaller Section
; ============================================================================

Section "Uninstall"
  ; Stop and remove service.
  nsExec::ExecToLog 'sc stop ${SERVICE_NAME}'
  Sleep 2000
  nsExec::ExecToLog '"$INSTDIR\dirq-agent.exe" uninstall'

  ; Remove firewall rule.
  nsExec::ExecToLog 'netsh advfirewall firewall delete rule name="DirQ Agent"'

  ; Remove files.
  Delete "$INSTDIR\dirq-agent.exe"
  Delete "$INSTDIR\LICENSE"
  Delete "$INSTDIR\README.md"
  Delete "$INSTDIR\uninstall.exe"
  RMDir "$INSTDIR"

  ; Remove config (ask user).
  MessageBox MB_YESNO "Remove configuration files in ${CONFIG_DIR}?" IDNO +3
    Delete "${CONFIG_DIR}\agent.conf"
    RMDir "${CONFIG_DIR}"

  ; Remove registry keys.
  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "Software\${PRODUCT_SHORT}"
SectionEnd
